// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	ping: (message: string) => typedError<Pong, CommandError>(__TAURI_INVOKE("ping", { message })),
	/**
	 *  Startup outcome (M5-4). The frontend calls this before rendering: when
	 *  `ok` is false it shows the recovery screen instead of the app.
	 */
	bootStatus: () => typedError<BootStatus, CommandError>(__TAURI_INVOKE("boot_status")),
	/**
	 *  Warnings raised while loading rule packs at startup (DESIGN §10.2).
	 *  Returns an empty list in recovery mode (no core context).
	 */
	getStartupWarnings: () => typedError<Warning[], CommandError>(__TAURI_INVOKE("get_startup_warnings")),
	/**
	 *  **Reset database** (FR-10.3). Clears every scanned repository, its health
	 *  and classification data, all findings, the advisory database, and the
	 *  outdated-version cache. Configured scan roots and preferences are kept.
	 *  The UI confirms before calling this; it is also the recovery action on
	 *  the fatal-error screen (DESIGN §15).
	 * 
	 *  In recovery mode (the core never initialised) there is no live database
	 *  to clear, so the `.db` files are deleted outright and the next launch
	 *  starts from a clean file.
	 */
	resetDatabase: () => typedError<null, CommandError>(__TAURI_INVOKE("reset_database")),
	/**
	 *  **Open data folder** (FR-10.3) — reveal the OS data directory (which
	 *  holds `repo-radar.db` and `logs/`) in the system file manager. Works in
	 *  recovery mode too.
	 */
	openDataFolder: () => typedError<null, CommandError>(__TAURI_INVOKE("open_data_folder")),
	/**
	 *  Read settings from the store, falling back to defaults when the value is
	 *  missing or unparseable.
	 */
	getSettings: () => typedError<Settings, CommandError>(__TAURI_INVOKE("get_settings")),
	/**  Replace the whole settings blob and flush to disk. */
	setSettings: (settings: Settings) => typedError<null, CommandError>(__TAURI_INVOKE("set_settings", { settings })),
	/**  List configured scan roots. */
	listScanRoots: () => typedError<ScanRoot[], CommandError>(__TAURI_INVOKE("list_scan_roots")),
	/**
	 *  Add a scan root after validating the path exists and is a readable
	 *  directory (M0-9). Idempotent on the path.
	 */
	addScanRoot: (path: string) => typedError<ScanRoot, CommandError>(__TAURI_INVOKE("add_scan_root", { path })),
	/**  Remove a scan root and everything derived from it (FK cascade). */
	removeScanRoot: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("remove_scan_root", { id })),
	/**
	 *  Enable or disable a scan root without discarding its scanned repos
	 *  (FR-10.1). A disabled root is skipped by the next scan.
	 */
	setScanRootEnabled: (id: number, enabled: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_scan_root_enabled", { id, enabled })),
	/**
	 *  Reorder scan roots (FR-10.1). `ordered_ids` is the full id list in the
	 *  desired top-to-bottom order.
	 */
	reorderScanRoots: (orderedIds: number[]) => typedError<null, CommandError>(__TAURI_INVOKE("reorder_scan_roots", { orderedIds })),
	/**
	 *  The built-in prune directories (FR-1.4). Shown read-only in Settings so
	 *  the user can see what the "additional" list adds to.
	 */
	builtinPruneDirs: () => typedError<string[], CommandError>(__TAURI_INVOKE("builtin_prune_dirs")),
	/**
	 *  Start a scan of every enabled scan root. Returns the scan id immediately;
	 *  the walk, analysis, and persistence run on a background thread and report
	 *  through `scan:*` events (DESIGN §12.1).
	 */
	scanStart: () => typedError<number, CommandError>(__TAURI_INVOKE("scan_start")),
	/**
	 *  Signal the running scan to stop. Already-persisted repos remain; the scan
	 *  row ends up `cancelled` (FR-1.9). A no-op if `scan_id` is not the scan in
	 *  flight.
	 */
	scanCancel: (scanId: number) => typedError<null, CommandError>(__TAURI_INVOKE("scan_cancel", { scanId })),
	/**
	 *  List repositories, filtered and sorted **in SQL** per `filter`
	 *  (DESIGN §12.1).
	 */
	listRepos: (filter: RepoFilter) => typedError<RepoListItem[], CommandError>(__TAURI_INVOKE("list_repos", { filter })),
	/**
	 *  Full detail for one repository: its record, language breakdown,
	 *  technologies, and submodule children.
	 */
	getRepoDetail: (id: number) => typedError<{
	repo: RepoRecord,
	languages: LanguageStat[],
	/**  Detected technologies, dependency-confirmed first (FR-2.3, FR-2.4). */
	technologies: TechDetail[],
	/**  Submodule children (FR-1.5) — shown here, never in the main list. */
	submodules: RepoRecord[],
	/**
	 *  The stored `health_breakdown` JSON, rendered directly by the UI so
	 *  the number shown and the number explained cannot drift (FR-6.9).
	 */
	healthBreakdown: string | null,
	/**  Compromise findings first, then vulnerabilities (FR-6.1). */
	findings: FindingDetail[],
} | null, CommandError>(__TAURI_INVOKE("get_repo_detail", { id })),
	/**
	 *  Set or clear the manual category override (FR-3.7). `category = None`
	 *  (or an unrecognised string) reverts to the computed value; the computed
	 *  category stays visible beside the override either way.
	 */
	setRepoCategory: (id: number, category: string | null) => typedError<null, CommandError>(__TAURI_INVOKE("set_repo_category", { id, category })),
	/**
	 *  Every figure the Dashboard renders, in one round trip (PRD §6). The
	 *  compromise banner (FR-6.3) keys off `compromised` being non-empty.
	 */
	dashboardStats: () => typedError<DashboardStats, CommandError>(__TAURI_INVOKE("dashboard_stats")),
	/**
	 *  The most recent scan and its persisted warnings (DESIGN §14.4). `None`
	 *  until a scan has run. The frontend uses it to tell "never scanned" from
	 *  "scanned, found nothing", and to badge repos that produced warnings even
	 *  after a reload.
	 */
	latestScanSummary: () => typedError<{
	id: number,
	status: ScanStatus,
	repoCount: number | null,
	startedAt: string,
	finishedAt: string | null,
	warnings: Warning[],
} | null, CommandError>(__TAURI_INVOKE("latest_scan_summary")),
	/**
	 *  Start an advisory sync in the background. Returns immediately; progress
	 *  via `sync:progress`, finish via `sync:complete`. A manual sync and the
	 *  scheduled sync cannot overlap (the `sync_lock`, DESIGN §12.3).
	 */
	syncAdvisories: (mode: SyncMode) => typedError<null, CommandError>(__TAURI_INVOKE("sync_advisories", { mode })),
	/**
	 *  Current advisory-database status (drives the freshness indicator and the
	 *  Advisories screen).
	 */
	getSyncStatus: () => typedError<SyncStatus, CommandError>(__TAURI_INVOKE("get_sync_status")),
	/**  Which repos a given advisory currently affects (cross-repo impact view). */
	listAdvisoryImpact: (advisoryId: string) => typedError<AdvisoryImpact[], CommandError>(__TAURI_INVOKE("list_advisory_impact", { advisoryId })),
	/**
	 *  FR-5.9 live query — opt-in, per-dependency. **This sends the package name
	 *  and version to `api.osv.dev`.** Never reachable from a scan or any
	 *  automatic path (M2-21).
	 */
	liveQuery: (ecosystem: string, name: string, version: string) => typedError<LiveQueryResult, CommandError>(__TAURI_INVOKE("live_query", { ecosystem, name, version })),
	/**
	 *  Check every dependency of a repo against its package registry (npm, PyPI,
	 *  crates.io, Go module proxy).
	 * 
	 *  **This contacts external registries.** The UI states so before the user
	 *  invokes it (FR-8.7). `force_refresh` bypasses the 24-hour result cache
	 *  (FR-8.5).
	 * 
	 *  Synchronous: the call blocks until every lookup resolves. The frontend
	 *  shows a pending state meanwhile.
	 */
	checkOutdated: (repoId: number, forceRefresh: boolean) => typedError<OutdatedReport, CommandError>(__TAURI_INVOKE("check_outdated", { repoId, forceRefresh })),
	/**  Every template available (built-ins + `<config>/prompts/*.j2`). */
	listPromptTemplates: () => typedError<TemplateInfo[], CommandError>(__TAURI_INVOKE("list_prompt_templates")),
	/**
	 *  The file selection tree for one repo (FR-9.3). Every path the user cannot
	 *  pick is still here, with the reason.
	 */
	promptFileListing: (repoId: number) => typedError<SelectionListing, CommandError>(__TAURI_INVOKE("prompt_file_listing", { repoId })),
	/**
	 *  Build the context, render the template, and return the full prompt plus a
	 *  token estimate. Does not copy or export anything.
	 */
	generatePrompt: (req: GeneratePromptRequest) => typedError<GeneratedPrompt, CommandError>(__TAURI_INVOKE("generate_prompt", { req })),
	/**
	 *  Write a rendered prompt to a user-chosen path. Refuses any path inside a
	 *  scan root or a scanned repository (FR-9.5, Principle 4) — the frontend
	 *  picks the path with the save dialog; this is the backstop.
	 */
	exportPrompt: (path: string, contents: string) => typedError<null, CommandError>(__TAURI_INVOKE("export_prompt", { path, contents })),
};

/** Events */
export const events = {
	scanComplete: makeEvent<ScanComplete>("scan-complete"),
	scanError: makeEvent<ScanError>("scan-error"),
	scanProgress: makeEvent<ScanProgress>("scan-progress"),
	scanRepoDone: makeEvent<ScanRepoDone>("scan-repo-done"),
	scanWarning: makeEvent<ScanWarning>("scan-warning"),
	syncComplete: makeEvent<SyncComplete>("sync-complete"),
	syncProgress: makeEvent<SyncProgress>("sync-progress"),
};

/* Types */
export type AdvisoryImpact = {
	repoId: number,
	repoName: string,
};

/**  The serializable view the `boot_status` command returns. */
export type BootStatus = {
	/**  `true` when analysis is available and the app can run normally. */
	ok: boolean,
	/**  Present when `!ok` — a human explanation for the recovery screen. */
	failure: string | null,
	schemaTooNew: boolean,
	/**  Present after an automatic recovery (corrupt file quarantined). */
	note: string | null,
};

/**  A `(label, count)` pair for a histogram or donut slice. */
export type Bucket = {
	label: string,
	count: number,
};

export type CommandError = 
/**  Unrecoverable — show the recovery screen (Reset database / Open data folder). */
{ tier: "fatal"; message: string } | 
/**  A whole operation failed; previous state is intact, offer retry. */
{ tier: "operation"; message: string } | 
/**  Anything else — a bad argument, a transient query error. */
{ tier: "internal"; message: string };

export type DashboardStats = {
	/**  Top-level repositories (submodule children excluded). */
	repoCount: number,
	dirtyCount: number,
	/**
	 *  Health band → repo count, ordered worst-first. A repo with no band
	 *  yet counts as `unknown` (never as healthy — DESIGN §14.4).
	 */
	healthDistribution: Bucket[],
	/**
	 *  Effective category → repo count, largest first. The manual override
	 *  (FR-3.7) wins over the computed value here.
	 */
	categoryDistribution: Bucket[],
	/**  Language → summed code lines across all repos, largest first (top 8). */
	languageDistribution: Bucket[],
	/**  Up to 5 repos with the oldest last commit. */
	stalest: RepoRef[],
	/**  Up to 5 repos with the lowest health score. */
	worstHealth: RepoRef[],
	/**
	 *  Every repo with at least one un-suppressed compromise finding. The
	 *  M3-7 banner renders iff this is non-empty (FR-6.3).
	 */
	compromised: RepoRef[],
};

export type EcosystemStatus = {
	ecosystem: string,
	advisoryCount: number,
	compromiseCount: number,
	lastSuccess: string | null,
	/**
	 *  `Thin` for crates.io and Go — the UI must caveat a clean result
	 *  there (spike §8.2.1, D1).
	 */
	malCoverage: MalCoverage,
};

/**
 *  Why a path is not offered for inclusion. Serialized tag-first so the UI
 *  can switch on `reason` and show the detail.
 */
export type ExclusionReason = 
/**  Inside a pruned directory (or the directory entry itself). */
{ reason: "pruned" } | 
/**  Matched `.gitignore` / `.git/info/exclude`. */
{ reason: "gitignored" } | 
/**  Extension is in the user's exclusion list (FR-10.1). */
{ reason: "extensionExcluded"; ext: string } | 
/**  Larger than `max_file_bytes`. */
{ reason: "oversized"; bytes: number } | 
/**  Contains a NUL byte or is not valid UTF-8 in its first 8 KiB. */
{ reason: "binary" } | 
/**  Could not be read (permissions, a broken symlink, a race). */
{ reason: "unreadable"; detail: string };

/**
 *  One finding for the Health tab (FR-6.9). Rendered from the stored data —
 *  the UI never recomputes a score.
 */
export type FindingDetail = {
	advisoryId: string,
	/**  `compromise` | `vulnerability`. */
	kind: string,
	severity: string,
	confidence: string,
	packageName: string,
	packageVersion: string,
	fixedVersion: string | null,
	summary: string,
	deduction: number | null,
};

/**
 *  How current the advisory data is, carried into prompts and shown in the
 *  global freshness indicator (FR-5.6).
 */
export type Freshness = 
/**  Never synced — findings are not trustworthy yet. */
"Never" | "Fresh" | 
/**  Older than 7 days. */
"Stale" | 
/**  Older than 30 days. */
"VeryStale";

export type GeneratePromptRequest = {
	templateId: string,
	/**
	 *  One id for a single-repo template, several for a cross-repo one. The
	 *  first is the repo files are embedded from.
	 */
	repoIds: number[],
	scope: ScopeContext,
	/**
	 *  Repo-relative paths (within the first repo) to embed. The frontend's
	 *  checkbox tree produces this; the backend re-checks every exclusion.
	 */
	selectedPaths?: string[],
};

export type GeneratedPrompt = {
	/**
	 *  The full rendered prompt — shown to the user before any copy or
	 *  export (FR-9.6).
	 */
	prompt: string,
	/**  `chars / 4`, always labelled an estimate in the UI (FR-9.4). */
	estimatedTokens: number,
	/**  The configured budget, for the over-budget warning. */
	tokenBudget: number,
	includedFiles: number,
	/**  Files that were asked for but withheld, each with its reason. */
	skippedFiles: SkippedFileInfo[],
	templateName: string,
};

/**
 *  Per-language aggregate for a repo (FR-2.1). Never a file list — memory
 *  stays bounded (DESIGN §17).
 */
export type LanguageStat = {
	language: string,
	code_lines: number,
	comment_lines: number,
	files: number,
	/**  Share of total code lines, 0..=100. */
	percentage: number | null,
};

export type LiveQueryResult = {
	advisoryIds: string[],
};

/**
 *  How complete OSV's malicious-package data is for an ecosystem. Hard-coded
 *  from the M2-12 spike; revisited each release.
 */
export type MalCoverage = 
/**  Systematic automated feeds — "no compromise findings" is meaningful. */
"Strong" | 
/**
 *  Only a handful of hand-filed reports. "No compromise findings" means
 *  "the few known cases were checked", not "this is clean". The UI must
 *  say so.
 */
"Thin";

export type OutdatedEntry = {
	/**  OSV/registry ecosystem id (`npm`, `PyPI`, `crates.io`, `Go`). */
	ecosystem: string,
	/**  Normalized name (the cache key). */
	name: string,
	/**  Name as written in the manifest, for display. */
	rawName: string,
	currentVersion: string,
	/**
	 *  Latest **stable** version from the registry, or `None` when the
	 *  lookup failed or the package is unknown.
	 */
	latestVersion: string | null,
	status: OutdatedStatus,
	isDirect: boolean,
	/**  `runtime` | `dev` | `build` | `optional` | `peer`. */
	scope: string,
	/**  Repo-relative manifest this dependency came from (FR-4.7). */
	manifestPath: string,
	/**
	 *  RFC3339 timestamp of the registry lookup the latest version came
	 *  from (may be up to `CACHE_TTL_HOURS` old — the UI shows the age,
	 *  FR-8.5).
	 */
	checkedAt: string,
	/**
	 *  True when `latest_version` came from `outdated_cache` rather than a
	 *  fresh request in this run.
	 */
	fromCache: boolean,
	/**  Registry error for this package, if the lookup failed. */
	error: string | null,
};

export type OutdatedReport = {
	repoId: number,
	/**  When this report was assembled. */
	generatedAt: string,
	/**  One row per distinct `(ecosystem, name, version)` in the repo. */
	entries: OutdatedEntry[],
	/**
	 *  Packages whose latest version could not be fetched this run (network
	 *  failures). Surfaced so a partial result is not mistaken for a clean
	 *  bill of health.
	 */
	failed: string[],
};

/**
 *  How far behind a dependency is. Derived by comparing the installed
 *  version's `(major, minor, patch)` against the registry's latest under the
 *  ecosystem's own version scheme (never a shared code path — DESIGN §8.5).
 */
export type OutdatedStatus = 
/**  Installed version is >= the registry's latest. */
"upToDate" | "outdatedPatch" | "outdatedMinor" | "outdatedMajor" | 
/**
 *  A version string would not parse, or the registry lookup failed — we
 *  could not decide. Never conflated with `UpToDate` (FR-4.8 spirit).
 */
"unknown";

/**
 *  Round-trips a value through the Rust↔TS boundary. Exists to prove the
 *  binding pipeline end to end (M0-5): change this struct in Rust and the
 *  generated `bindings.ts` must change with no hand-editing.
 */
export type Pong = {
	echo: string,
	schema_version: number,
	pid: number,
};

/**  How many repos a template expects. */
export type RepoArity = 
/**  Exactly one repo (T2, T3). */
"single" | 
/**  Two or more repos (T1). */
"multi";

export type RepoDetail = {
	repo: RepoRecord,
	languages: LanguageStat[],
	/**  Detected technologies, dependency-confirmed first (FR-2.3, FR-2.4). */
	technologies: TechDetail[],
	/**  Submodule children (FR-1.5) — shown here, never in the main list. */
	submodules: RepoRecord[],
	/**
	 *  The stored `health_breakdown` JSON, rendered directly by the UI so
	 *  the number shown and the number explained cannot drift (FR-6.9).
	 */
	healthBreakdown: string | null,
	/**  Compromise findings first, then vulnerabilities (FR-6.1). */
	findings: FindingDetail[],
};

/**
 *  Typed filter for `list_repos`. A struct rather than loose query params so
 *  the whole query — filtering *and* sorting — executes in SQLite and the
 *  client never receives rows it will just hide (DESIGN §12.1).
 */
export type RepoFilter = {
	/**  Free-text match against name and path (case-insensitive substring). */
	search?: string | null,
	/**  Only repos whose primary language equals this. */
	language?: string | null,
	/**  Only repos with a dirty working tree. */
	dirtyOnly?: boolean,
	/**  Include bare repos (default: included). */
	includeBare?: boolean,
	sort?: RepoSort,
	descending?: boolean,
};

/**  Compact per-repo row for lists and the scan reporter. */
export type RepoListItem = {
	id: number,
	name: string,
	path: string,
	isBare: boolean,
	branch: string | null,
	lastCommitAt: string | null,
	dirty: boolean,
	primaryLanguage: string | null,
	healthScore: number | null,
	/**  `unknown` / `critical` / `poor` / `fair` / `good` / `excellent`. */
	healthBand: string | null,
	/**
	 *  Confirmed compromise findings and ordinary vulnerabilities are kept
	 *  in **separate columns** (FR-6.1, M2-23) — a combined "issues" count
	 *  would destroy the distinction the health model exists to make.
	 */
	compromiseCount: number,
	vulnerabilityCount: number,
};

/**  Full git columns for one repo, for the detail view. */
export type RepoRecord = {
	id: number,
	name: string,
	path: string,
	isBare: boolean,
	isMonorepo: boolean,
	parentRepoId: number | null,
	headSha: string | null,
	branch: string | null,
	lastCommitAt: string | null,
	lastCommitSummary: string | null,
	commits90d: number | null,
	commitsTotal: number | null,
	authorCount: number | null,
	dirtyModified: number | null,
	dirtyStaged: number | null,
	dirtyUntracked: number | null,
	ahead: number | null,
	behind: number | null,
	remoteUrl: string | null,
	branchCount: number | null,
	hasStash: boolean | null,
	lastScannedAt: string | null,
	healthScore: number | null,
	healthBand: string | null,
	/**  The *computed* category. Stays visible even when overridden (FR-3.7). */
	category: string | null,
	/**  `low` / `medium` / `high`. */
	categoryConfidence: string | null,
	/**
	 *  The `category_scores` JSON — the full per-rule / per-category
	 *  breakdown, rendered directly by the explainability UI (FR-3.6).
	 */
	categoryScores: string | null,
	/**  A manual override (FR-3.7); `None` when the computed value stands. */
	categoryManual: string | null,
};

/**  A repo referenced from one of the "needs attention" lists. */
export type RepoRef = {
	id: number,
	name: string,
	/**  Present on the stalest list. */
	lastCommitAt: string | null,
	/**  Present on the worst-health list. */
	healthScore: number | null,
	healthBand: string | null,
	/**  Confirmed-compromise finding count (0 unless this is a compromise row). */
	compromiseCount: number,
};

/**  Sort key for the repo list. Sorting happens in SQL (DESIGN §12.1). */
export type RepoSort = "name" | "last_commit" | "primary_language";

/**  `scan:complete`. */
export type ScanComplete = {
	scanId: number,
	reposScanned: number,
	warnings: number,
	cancelled: boolean,
};

/**  `scan:error` — scan-level failure only, never per-repo. */
export type ScanError = {
	message: string,
};

/**  `scan:progress` — drives the global progress bar. */
export type ScanProgress = {
	scanId: number,
	discovered: number,
	completed: number,
};

/**
 *  `scan:repo_done` — one repo finished; the UI invalidates `['repos']` and
 *  `['repo', id]` (DESIGN §14.1), populating the list incrementally.
 */
export type ScanRepoDone = {
	scanId: number,
	repoId: number,
	name: string,
	path: string,
	warningCount: number,
};

/**  A configured scan root (FR-10.1). `id` is the SQLite rowid. */
export type ScanRoot = {
	id: number,
	path: string,
	enabled: boolean,
	/**  RFC 3339 timestamp. */
	added_at: string,
	/**  Display order in the settings list (FR-10.1). Lower sorts first. */
	position: number,
};

export type ScanStatus = "running" | "complete" | "cancelled" | "failed";

/**
 *  A summary of the most recent scan, for the frontend's empty/degraded
 *  states (DESIGN §14.4): it tells "never scanned" from "scanned, found
 *  nothing", and carries the persisted warning list so a repo with warnings
 *  stays distinguishable after a reload (M1-8, M5-4).
 */
export type ScanSummary = {
	id: number,
	status: ScanStatus,
	repoCount: number | null,
	startedAt: string,
	finishedAt: string | null,
	warnings: Warning[],
};

/**  `scan:warning` — a recoverable problem, surfaced as it occurs. */
export type ScanWarning = {
	scanId: number,
	warning: Warning,
};

/**
 *  What the user selected to include (DESIGN §11.2). Also a Tauri command
 *  argument, so this one is camelCase: templates see `scope.kind` as
 *  `wholeRepo | directory | files | diff`.
 */
export type ScopeContext = 
/**  Everything selectable in the repo. */
{ kind: "wholeRepo" } | 
/**  A single subtree. */
{ kind: "directory"; path: string } | 
/**  An explicit list of files. */
{ kind: "files"; paths: string[] } | 
/**  A diff supplied as text (e.g. `git diff` output). */
{ kind: "diff"; description: string };

/**  One row in the selection tree. */
export type SelectableFile = {
	/**  Repo-relative, `/`-separated. */
	path: string,
	isDir: boolean,
	bytes: number,
	language: string | null,
	/**  `None` when the file is selectable; `Some` explains why it is not. */
	excluded: ExclusionReason | null,
};

export type SelectionListing = {
	repoRoot: string,
	/**
	 *  Sorted by path. Directories that were pruned appear once, with
	 *  `excluded = Pruned`, and their contents are not listed.
	 */
	files: SelectableFile[],
	/**  `true` when `max_entries` was hit and the listing is incomplete. */
	truncated: boolean,
};

export type Settings = {
	/**
	 *  Directory names pruned during discovery and language stats (FR-1.4).
	 *  Added to the built-in [`DEFAULT_PRUNE_LIST`], not a replacement.
	 */
	pruneList?: string[],
	/**
	 *  File extensions (no dot, lowercase) withheld from the prompt file
	 *  picker in addition to the content-sniffed binary check (FR-10.1).
	 */
	excludedExtensions?: string[],
	/**
	 *  How often the scheduled advisory sync runs (DESIGN §13.2). `0` means
	 *  **manual only** — the scheduler performs no automatic sync (FR-10.1,
	 *  "daily / manual only").
	 */
	syncIntervalHours?: number,
	/**  Prompt token budget for the estimator (FR-9.4). */
	tokenBudget?: number,
	theme?: Theme,
};

export type SkippedFileInfo = {
	path: string,
	reason: ExclusionReason,
};

/**  `sync:complete` — triggers a findings refresh in the UI. */
export type SyncComplete = {
	ok: boolean,
	message: string | null,
};

export type SyncMode = "full" | "incremental";

/**  `sync:progress`. */
export type SyncProgress = {
	ecosystem: string,
	phase: string,
	done: number,
	total: number,
};

export type SyncStatus = {
	/**  RFC 3339 time of the most recent `complete` sync, any ecosystem. */
	lastSuccess: string | null,
	/**
	 *  `false` on a fresh install — health is *unknown*, not healthy
	 *  (DESIGN §14.4, M2-22).
	 */
	everSynced: boolean,
	advisoryCount: number,
	freshness: Freshness,
	/**  The most recent sync error, if the last attempt failed. */
	lastError: string | null,
	ecosystems: EcosystemStatus[],
};

/**
 *  One detected technology for the detail view (FR-2.3). `evidence` entries
 *  are prefixed `dependency:` or `file:`; a detection with no `dependency:`
 *  entry renders with lower prominence (FR-2.4).
 */
export type TechDetail = {
	tech: string,
	kind: string,
	evidence: string[],
};

/**  One entry in the template picker. */
export type TemplateInfo = {
	/**  Stable id — the file stem. Passed back to [`load_source`]. */
	id: string,
	name: string,
	description: string,
	source: TemplateSource,
	arity: RepoArity,
	/**
	 *  `true` when this template embeds file bodies (T2/T3) and therefore
	 *  drives the file picker; `false` for metadata-only comparisons (T1).
	 */
	usesFiles: boolean,
};

export type TemplateSource = "builtIn" | "user";

export type Theme = "light" | "dark" | "system";

/**
 *  A recoverable, per-item problem. Nothing in a scan is fatal at the scan
 *  level (FR-1.10, FR-4.8): every recoverable failure becomes one of these,
 *  is persisted with the scan, and badges the affected repo. Silent
 *  degradation — a repo whose lockfile failed to parse looking identical to
 *  a clean one — is exactly what this type exists to prevent.
 */
export type Warning = {
	scope: WarningScope,
	kind: WarningKind,
	message: string,
};

export type WarningKind = "PermissionDenied" | "ParseFailed" | "GitTimeout" | "GitError" | "UnparseableVersion" | "RulePackInvalid" | "Panic" | "Other";

export type WarningScope = "Scan" | ({ Repo: string }) & { File?: never } | ({ File: string }) & { Repo?: never };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

