// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	ping: (message: string) => typedError<Pong, CommandError>(__TAURI_INVOKE("ping", { message })),
	/**
	 *  Warnings raised while loading rule packs at startup (DESIGN §10.2). Wired
	 *  up now so the [`Warning`] type is exercised across the boundary (M0-7);
	 *  the scan surfaces per-repo warnings the same way from M1-8.
	 */
	getStartupWarnings: () => typedError<Warning[], CommandError>(__TAURI_INVOKE("get_startup_warnings")),
	/**
	 *  Read settings from the store, falling back to defaults when the value is
	 *  missing or unparseable.
	 */
	getSettings: () => typedError<Settings, CommandError>(__TAURI_INVOKE("get_settings")),
	/**  Replace the whole settings blob and flush to disk. */
	setSettings: (settings: Settings) => typedError<null, CommandError>(__TAURI_INVOKE("set_settings", { settings })),
	/**  List configured scan roots. */
	listScanRoots: () => typedError<ScanRoot[], CommandError>(__TAURI_INVOKE("list_scan_roots")),
	/**
	 *  Add a scan root after validating the path exists and is a readable
	 *  directory (M0-9). Idempotent on the path.
	 */
	addScanRoot: (path: string) => typedError<ScanRoot, CommandError>(__TAURI_INVOKE("add_scan_root", { path })),
	/**  Remove a scan root and everything derived from it (FK cascade). */
	removeScanRoot: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("remove_scan_root", { id })),
};

/** Events */
export const events = {
	scanComplete: makeEvent<ScanComplete>("scan-complete"),
	scanError: makeEvent<ScanError>("scan-error"),
	scanProgress: makeEvent<ScanProgress>("scan-progress"),
	scanRepoDone: makeEvent<ScanRepoDone>("scan-repo-done"),
	scanWarning: makeEvent<ScanWarning>("scan-warning"),
	syncComplete: makeEvent<SyncComplete>("sync-complete"),
	syncProgress: makeEvent<SyncProgress>("sync-progress"),
};

/* Types */
export type CommandError = 
/**  Unrecoverable — show the recovery screen (Reset database / Open data folder). */
{ tier: "fatal"; message: string } | 
/**  A whole operation failed; previous state is intact, offer retry. */
{ tier: "operation"; message: string } | 
/**  Anything else — a bad argument, a transient query error. */
{ tier: "internal"; message: string };

/**
 *  Round-trips a value through the Rust↔TS boundary. Exists to prove the
 *  binding pipeline end to end (M0-5): change this struct in Rust and the
 *  generated `bindings.ts` must change with no hand-editing.
 */
export type Pong = {
	echo: string,
	schema_version: number,
	pid: number,
};

/**  `scan:complete`. */
export type ScanComplete = {
	scan_id: number,
	repos_scanned: number,
	warnings: number,
	cancelled: boolean,
};

/**  `scan:error` — scan-level failure only, never per-repo. */
export type ScanError = {
	message: string,
};

/**  `scan:progress` — drives the global progress bar. */
export type ScanProgress = {
	scan_id: number,
	discovered: number,
	completed: number,
};

/**
 *  `scan:repo_done` — one repo finished; the UI invalidates `['repos']` and
 *  `['repo', id]` (DESIGN §14.1), populating the list incrementally.
 */
export type ScanRepoDone = {
	scan_id: number,
	repo_id: number,
	name: string,
	path: string,
	warning_count: number,
};

/**  A configured scan root (FR-10.1). `id` is the SQLite rowid. */
export type ScanRoot = {
	id: number,
	path: string,
	enabled: boolean,
	/**  RFC 3339 timestamp. */
	added_at: string,
};

/**  `scan:warning` — a recoverable problem, surfaced as it occurs. */
export type ScanWarning = {
	scan_id: number,
	warning: Warning,
};

export type Settings = {
	/**  Directory names pruned during discovery and language stats (FR-1.4). */
	pruneList?: string[],
	/**  How often the scheduled advisory sync runs (DESIGN §13.2). */
	syncIntervalHours?: number,
	/**  Prompt token budget for the estimator (FR-9.4). */
	tokenBudget?: number,
	theme?: Theme,
};

/**  `sync:complete` — triggers a findings refresh in the UI. */
export type SyncComplete = {
	ok: boolean,
	message: string | null,
};

/**  `sync:progress`. */
export type SyncProgress = {
	ecosystem: string,
	phase: string,
	done: number,
	total: number,
};

export type Theme = "light" | "dark" | "system";

/**
 *  A recoverable, per-item problem. Nothing in a scan is fatal at the scan
 *  level (FR-1.10, FR-4.8): every recoverable failure becomes one of these,
 *  is persisted with the scan, and badges the affected repo. Silent
 *  degradation — a repo whose lockfile failed to parse looking identical to
 *  a clean one — is exactly what this type exists to prevent.
 */
export type Warning = {
	scope: WarningScope,
	kind: WarningKind,
	message: string,
};

export type WarningKind = "PermissionDenied" | "ParseFailed" | "GitTimeout" | "GitError" | "UnparseableVersion" | "RulePackInvalid" | "Panic" | "Other";

export type WarningScope = "Scan" | ({ Repo: string }) & { File?: never } | ({ File: string }) & { Repo?: never };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

