// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	ping: (message: string) => typedError<Pong, CommandError>(__TAURI_INVOKE("ping", { message })),
	/**
	 *  Warnings raised while loading rule packs at startup (DESIGN §10.2). Wired
	 *  up now so the [`Warning`] type is exercised across the boundary (M0-7);
	 *  the scan surfaces per-repo warnings the same way from M1-8.
	 */
	getStartupWarnings: () => typedError<Warning[], CommandError>(__TAURI_INVOKE("get_startup_warnings")),
	/**
	 *  Read settings from the store, falling back to defaults when the value is
	 *  missing or unparseable.
	 */
	getSettings: () => typedError<Settings, CommandError>(__TAURI_INVOKE("get_settings")),
	/**  Replace the whole settings blob and flush to disk. */
	setSettings: (settings: Settings) => typedError<null, CommandError>(__TAURI_INVOKE("set_settings", { settings })),
	/**  List configured scan roots. */
	listScanRoots: () => typedError<ScanRoot[], CommandError>(__TAURI_INVOKE("list_scan_roots")),
	/**
	 *  Add a scan root after validating the path exists and is a readable
	 *  directory (M0-9). Idempotent on the path.
	 */
	addScanRoot: (path: string) => typedError<ScanRoot, CommandError>(__TAURI_INVOKE("add_scan_root", { path })),
	/**  Remove a scan root and everything derived from it (FK cascade). */
	removeScanRoot: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("remove_scan_root", { id })),
	/**
	 *  Start a scan of every enabled scan root. Returns the scan id immediately;
	 *  the walk, analysis, and persistence run on a background thread and report
	 *  through `scan:*` events (DESIGN §12.1).
	 */
	scanStart: () => typedError<number, CommandError>(__TAURI_INVOKE("scan_start")),
	/**
	 *  Signal the running scan to stop. Already-persisted repos remain; the scan
	 *  row ends up `cancelled` (FR-1.9). A no-op if `scan_id` is not the scan in
	 *  flight.
	 */
	scanCancel: (scanId: number) => typedError<null, CommandError>(__TAURI_INVOKE("scan_cancel", { scanId })),
	/**
	 *  List repositories, filtered and sorted **in SQL** per `filter`
	 *  (DESIGN §12.1).
	 */
	listRepos: (filter: RepoFilter) => typedError<RepoListItem[], CommandError>(__TAURI_INVOKE("list_repos", { filter })),
	/**
	 *  Full detail for one repository: its record, language breakdown, and
	 *  submodule children.
	 */
	getRepoDetail: (id: number) => typedError<{
	repo: RepoRecord,
	languages: LanguageStat[],
	/**  Submodule children (FR-1.5) — shown here, never in the main list. */
	submodules: RepoRecord[],
	/**
	 *  The stored `health_breakdown` JSON, rendered directly by the UI so
	 *  the number shown and the number explained cannot drift (FR-6.9).
	 */
	healthBreakdown: string | null,
	/**  Compromise findings first, then vulnerabilities (FR-6.1). */
	findings: FindingDetail[],
} | null, CommandError>(__TAURI_INVOKE("get_repo_detail", { id })),
	/**
	 *  Start an advisory sync in the background. Returns immediately; progress
	 *  via `sync:progress`, finish via `sync:complete`. A manual sync and the
	 *  scheduled sync cannot overlap (the `sync_lock`, DESIGN §12.3).
	 */
	syncAdvisories: (mode: SyncMode) => typedError<null, CommandError>(__TAURI_INVOKE("sync_advisories", { mode })),
	/**
	 *  Current advisory-database status (drives the freshness indicator and the
	 *  Advisories screen).
	 */
	getSyncStatus: () => typedError<SyncStatus, CommandError>(__TAURI_INVOKE("get_sync_status")),
	/**  Which repos a given advisory currently affects (cross-repo impact view). */
	listAdvisoryImpact: (advisoryId: string) => typedError<AdvisoryImpact[], CommandError>(__TAURI_INVOKE("list_advisory_impact", { advisoryId })),
	/**
	 *  FR-5.9 live query — opt-in, per-dependency. **This sends the package name
	 *  and version to `api.osv.dev`.** Never reachable from a scan or any
	 *  automatic path (M2-21).
	 */
	liveQuery: (ecosystem: string, name: string, version: string) => typedError<LiveQueryResult, CommandError>(__TAURI_INVOKE("live_query", { ecosystem, name, version })),
};

/** Events */
export const events = {
	scanComplete: makeEvent<ScanComplete>("scan-complete"),
	scanError: makeEvent<ScanError>("scan-error"),
	scanProgress: makeEvent<ScanProgress>("scan-progress"),
	scanRepoDone: makeEvent<ScanRepoDone>("scan-repo-done"),
	scanWarning: makeEvent<ScanWarning>("scan-warning"),
	syncComplete: makeEvent<SyncComplete>("sync-complete"),
	syncProgress: makeEvent<SyncProgress>("sync-progress"),
};

/* Types */
export type AdvisoryImpact = {
	repoId: number,
	repoName: string,
};

export type CommandError = 
/**  Unrecoverable — show the recovery screen (Reset database / Open data folder). */
{ tier: "fatal"; message: string } | 
/**  A whole operation failed; previous state is intact, offer retry. */
{ tier: "operation"; message: string } | 
/**  Anything else — a bad argument, a transient query error. */
{ tier: "internal"; message: string };

export type EcosystemStatus = {
	ecosystem: string,
	advisoryCount: number,
	compromiseCount: number,
	lastSuccess: string | null,
	/**
	 *  `Thin` for crates.io and Go — the UI must caveat a clean result
	 *  there (spike §8.2.1, D1).
	 */
	malCoverage: MalCoverage,
};

/**
 *  One finding for the Health tab (FR-6.9). Rendered from the stored data —
 *  the UI never recomputes a score.
 */
export type FindingDetail = {
	advisoryId: string,
	/**  `compromise` | `vulnerability`. */
	kind: string,
	severity: string,
	confidence: string,
	packageName: string,
	packageVersion: string,
	fixedVersion: string | null,
	summary: string,
	deduction: number | null,
};

/**
 *  How current the advisory data is, carried into prompts and shown in the
 *  global freshness indicator (FR-5.6).
 */
export type Freshness = 
/**  Never synced — findings are not trustworthy yet. */
"Never" | "Fresh" | 
/**  Older than 7 days. */
"Stale" | 
/**  Older than 30 days. */
"VeryStale";

/**
 *  Per-language aggregate for a repo (FR-2.1). Never a file list — memory
 *  stays bounded (DESIGN §17).
 */
export type LanguageStat = {
	language: string,
	code_lines: number,
	comment_lines: number,
	files: number,
	/**  Share of total code lines, 0..=100. */
	percentage: number | null,
};

export type LiveQueryResult = {
	advisoryIds: string[],
};

/**
 *  How complete OSV's malicious-package data is for an ecosystem. Hard-coded
 *  from the M2-12 spike; revisited each release.
 */
export type MalCoverage = 
/**  Systematic automated feeds — "no compromise findings" is meaningful. */
"Strong" | 
/**
 *  Only a handful of hand-filed reports. "No compromise findings" means
 *  "the few known cases were checked", not "this is clean". The UI must
 *  say so.
 */
"Thin";

/**
 *  Round-trips a value through the Rust↔TS boundary. Exists to prove the
 *  binding pipeline end to end (M0-5): change this struct in Rust and the
 *  generated `bindings.ts` must change with no hand-editing.
 */
export type Pong = {
	echo: string,
	schema_version: number,
	pid: number,
};

export type RepoDetail = {
	repo: RepoRecord,
	languages: LanguageStat[],
	/**  Submodule children (FR-1.5) — shown here, never in the main list. */
	submodules: RepoRecord[],
	/**
	 *  The stored `health_breakdown` JSON, rendered directly by the UI so
	 *  the number shown and the number explained cannot drift (FR-6.9).
	 */
	healthBreakdown: string | null,
	/**  Compromise findings first, then vulnerabilities (FR-6.1). */
	findings: FindingDetail[],
};

/**
 *  Typed filter for `list_repos`. A struct rather than loose query params so
 *  the whole query — filtering *and* sorting — executes in SQLite and the
 *  client never receives rows it will just hide (DESIGN §12.1).
 */
export type RepoFilter = {
	/**  Free-text match against name and path (case-insensitive substring). */
	search?: string | null,
	/**  Only repos whose primary language equals this. */
	language?: string | null,
	/**  Only repos with a dirty working tree. */
	dirtyOnly?: boolean,
	/**  Include bare repos (default: included). */
	includeBare?: boolean,
	sort?: RepoSort,
	descending?: boolean,
};

/**  Compact per-repo row for lists and the scan reporter. */
export type RepoListItem = {
	id: number,
	name: string,
	path: string,
	isBare: boolean,
	branch: string | null,
	lastCommitAt: string | null,
	dirty: boolean,
	primaryLanguage: string | null,
	healthScore: number | null,
	/**  `unknown` / `critical` / `poor` / `fair` / `good` / `excellent`. */
	healthBand: string | null,
	/**
	 *  Confirmed compromise findings and ordinary vulnerabilities are kept
	 *  in **separate columns** (FR-6.1, M2-23) — a combined "issues" count
	 *  would destroy the distinction the health model exists to make.
	 */
	compromiseCount: number,
	vulnerabilityCount: number,
};

/**  Full git columns for one repo, for the detail view. */
export type RepoRecord = {
	id: number,
	name: string,
	path: string,
	isBare: boolean,
	isMonorepo: boolean,
	parentRepoId: number | null,
	headSha: string | null,
	branch: string | null,
	lastCommitAt: string | null,
	lastCommitSummary: string | null,
	commits90d: number | null,
	commitsTotal: number | null,
	authorCount: number | null,
	dirtyModified: number | null,
	dirtyStaged: number | null,
	dirtyUntracked: number | null,
	ahead: number | null,
	behind: number | null,
	remoteUrl: string | null,
	branchCount: number | null,
	hasStash: boolean | null,
	lastScannedAt: string | null,
	healthScore: number | null,
	healthBand: string | null,
	category: string | null,
};

/**  Sort key for the repo list. Sorting happens in SQL (DESIGN §12.1). */
export type RepoSort = "name" | "last_commit" | "primary_language";

/**  `scan:complete`. */
export type ScanComplete = {
	scanId: number,
	reposScanned: number,
	warnings: number,
	cancelled: boolean,
};

/**  `scan:error` — scan-level failure only, never per-repo. */
export type ScanError = {
	message: string,
};

/**  `scan:progress` — drives the global progress bar. */
export type ScanProgress = {
	scanId: number,
	discovered: number,
	completed: number,
};

/**
 *  `scan:repo_done` — one repo finished; the UI invalidates `['repos']` and
 *  `['repo', id]` (DESIGN §14.1), populating the list incrementally.
 */
export type ScanRepoDone = {
	scanId: number,
	repoId: number,
	name: string,
	path: string,
	warningCount: number,
};

/**  A configured scan root (FR-10.1). `id` is the SQLite rowid. */
export type ScanRoot = {
	id: number,
	path: string,
	enabled: boolean,
	/**  RFC 3339 timestamp. */
	added_at: string,
};

/**  `scan:warning` — a recoverable problem, surfaced as it occurs. */
export type ScanWarning = {
	scanId: number,
	warning: Warning,
};

export type Settings = {
	/**  Directory names pruned during discovery and language stats (FR-1.4). */
	pruneList?: string[],
	/**  How often the scheduled advisory sync runs (DESIGN §13.2). */
	syncIntervalHours?: number,
	/**  Prompt token budget for the estimator (FR-9.4). */
	tokenBudget?: number,
	theme?: Theme,
};

/**  `sync:complete` — triggers a findings refresh in the UI. */
export type SyncComplete = {
	ok: boolean,
	message: string | null,
};

export type SyncMode = "full" | "incremental";

/**  `sync:progress`. */
export type SyncProgress = {
	ecosystem: string,
	phase: string,
	done: number,
	total: number,
};

export type SyncStatus = {
	/**  RFC 3339 time of the most recent `complete` sync, any ecosystem. */
	lastSuccess: string | null,
	/**
	 *  `false` on a fresh install — health is *unknown*, not healthy
	 *  (DESIGN §14.4, M2-22).
	 */
	everSynced: boolean,
	advisoryCount: number,
	freshness: Freshness,
	/**  The most recent sync error, if the last attempt failed. */
	lastError: string | null,
	ecosystems: EcosystemStatus[],
};

export type Theme = "light" | "dark" | "system";

/**
 *  A recoverable, per-item problem. Nothing in a scan is fatal at the scan
 *  level (FR-1.10, FR-4.8): every recoverable failure becomes one of these,
 *  is persisted with the scan, and badges the affected repo. Silent
 *  degradation — a repo whose lockfile failed to parse looking identical to
 *  a clean one — is exactly what this type exists to prevent.
 */
export type Warning = {
	scope: WarningScope,
	kind: WarningKind,
	message: string,
};

export type WarningKind = "PermissionDenied" | "ParseFailed" | "GitTimeout" | "GitError" | "UnparseableVersion" | "RulePackInvalid" | "Panic" | "Other";

export type WarningScope = "Scan" | ({ Repo: string }) & { File?: never } | ({ File: string }) & { Repo?: never };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

